import { z } from 'zod';
import { requireApiUser } from '@/lib/server/auth';
import { contentFromText, db, id, now } from '@/lib/server/data';
import { errorResponse, json } from '@/lib/server/http';
import { getFilesBucket } from '@/lib/server/runtime';
const fields = z.object({ name: z.string().trim().min(1).max(160), language: z.enum(['zh','en']), extractedText: z.string().trim().min(30).max(200_000), confirmed: z.literal('true') });
export async function POST(request: Request) { try { const user = await requireApiUser(); const form = await request.formData(); const file = form.get('file'); if (!(file instanceof File)) return json({ error: '请选择 PDF 或 DOCX 文件。' }, { status: 400 }); if (file.size > 10 * 1024 * 1024) return json({ error: '文件不能超过 10MB。' }, { status: 413 }); const ext = file.name.toLowerCase().split('.').pop(); if (!['pdf','docx'].includes(ext || '')) return json({ error: '仅支持 PDF 和 DOCX。' }, { status: 400 }); const parsed = fields.safeParse({ name: form.get('name'), language: form.get('language'), extractedText: form.get('extractedText'), confirmed: form.get('confirmed') }); if (!parsed.success) return json({ error: parsed.error.issues[0]?.message || '请先核对解析内容。' }, { status: 400 }); const timestamp = now(), fileId = id('file'), resumeId = id('resume'), versionId = id('rv'); const objectKey = `${user.userId}/source/${fileId}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`; await getFilesBucket().put(objectKey, await file.arrayBuffer(), { httpMetadata: { contentType: file.type || 'application/octet-stream' } }); const content = contentFromText(parsed.data.extractedText, parsed.data.language); await db().batch([
      db().prepare(`INSERT INTO stored_files (id,user_id,filename,object_key,mime_type,size,kind,owner_id,created_at) VALUES (?,?,?,?,?,?,'source',?,?)`).bind(fileId,user.userId,file.name,objectKey,file.type || 'application/octet-stream',file.size,resumeId,timestamp),
      db().prepare(`INSERT INTO resumes (id,user_id,name,language,source_file_id,is_base,current_version_id,created_at,updated_at) VALUES (?,?,?,?,?,1,?,?,?)`).bind(resumeId,user.userId,parsed.data.name,parsed.data.language,fileId,versionId,timestamp,timestamp),
      db().prepare(`INSERT INTO resume_versions (id,user_id,resume_id,job_id,parent_version_id,version_number,content_json,source_text,created_at) VALUES (?,?,?,NULL,NULL,1,?,?,?)`).bind(versionId,user.userId,resumeId,JSON.stringify(content),parsed.data.extractedText,timestamp),
    ]); return json({ resume: { id: resumeId, versionId } }, { status: 201 }); } catch (error) { return errorResponse(error); } }
