import { ArrowUpRight, BriefcaseBusiness, FileText, Gauge, Sparkles, WandSparkles } from 'lucide-react';
import { AppShell } from '@/components/app-shell';
import { Badge } from '@/components/ui/badge';
import { jobStatusLabels, jobStatuses } from '@/lib/product-types';
import { requirePageUser } from '@/lib/server/auth';
import { listJobs, listResumes } from '@/lib/server/data';

export const dynamic = 'force-dynamic';

export default async function Home() {
  const user = await requirePageUser('/');
  const [jobs, resumes] = await Promise.all([listJobs(user.userId), listResumes(user.userId)]);
  const counts = Object.fromEntries(jobStatuses.map((s) => [s, jobs.filter((j) => j.status === s).length]));
  return <AppShell title={`你好，${user.fullName || '继续推进今天的投递'}`} eyebrow="2027 届秋招 · 个人空间"><div className="space-y-8 pb-20 lg:pb-0">
    <section className="grid gap-4 xl:grid-cols-[minmax(0,1.55fr)_minmax(320px,.8fr)]">
      <div className="relative overflow-hidden rounded-[28px] border border-white/10 bg-[#071b2b] p-6 text-white shadow-[0_28px_90px_-45px_rgba(2,20,33,.9)] sm:p-8"><div className="pointer-events-none absolute -right-20 -top-28 size-72 rounded-full border-[42px] border-cyan-300/[.05]" /><div className="pointer-events-none absolute bottom-0 right-24 size-40 rounded-full bg-emerald-300/[.07] blur-3xl" /><Badge className="border border-cyan-200/15 bg-cyan-200/10 text-cyan-100"><Sparkles /> AI 定向优化</Badge><h2 className="relative mt-5 max-w-xl text-[28px] font-semibold leading-[1.18] tracking-[-0.035em] sm:text-[34px]">从岗位 JD 到可投递简历，<br />每一步都清楚可控。</h2><p className="relative mt-4 max-w-lg text-sm leading-7 text-slate-300">粘贴岗位描述，逐条确认修改建议，生成岗位版简历和官网填写材料包。</p><div className="relative mt-7 flex flex-wrap gap-3"><a href="/jobs/new" data-interactive="true" className="pressable inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-cyan-300 to-emerald-300 px-4 py-3 text-sm font-semibold text-[#06232c] shadow-[0_12px_30px_-12px_rgba(45,212,191,.8)]"><WandSparkles className="size-4" />开始匹配岗位</a><a href="/resumes" data-interactive="true" className="pressable rounded-xl border border-white/15 bg-white/[.06] px-4 py-3 text-sm font-medium text-white backdrop-blur hover:bg-white/[.1]">管理简历版本</a></div></div>
      <div className="surface-card flex flex-col justify-between overflow-hidden p-6"><div><div className="flex items-center justify-between"><span className="icon-tile"><Gauge className="size-5" /></span><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[11px] font-semibold text-emerald-700">实时概览</span></div><p className="mt-5 text-sm text-muted-foreground">当前工作区</p><p className="mt-2 text-[25px] font-semibold tracking-[-0.03em]">{jobs.length} 个岗位 · {resumes.length} 份简历</p></div><div className="mt-8 grid grid-cols-3 gap-2 text-center"><Metric value={counts.wishlist} label="待投递" /><Metric value={counts.interview} label="面试" /><Metric value={counts.offer} label="Offer" /></div></div>
    </section>
    <section><div className="mb-4 flex items-end justify-between"><div><p className="section-kicker">PIPELINE</p><h2 className="mt-1 text-lg font-semibold tracking-[-0.02em]">投递进展</h2></div><a href="/pipeline" data-interactive="true" className="pressable text-sm font-medium text-muted-foreground hover:text-primary">查看看板 →</a></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-6">{jobStatuses.map((status) => <a key={status} href="/pipeline" data-interactive="true" className="interactive-card rounded-2xl border bg-white p-4"><span className="text-sm text-muted-foreground">{jobStatusLabels[status]}</span><p className="mt-3 text-2xl font-semibold tracking-[-0.03em]">{counts[status]}</p></a>)}</div></section>
    <section><div className="mb-4 flex items-end justify-between"><div><p className="section-kicker">RECENT</p><h2 className="mt-1 text-lg font-semibold tracking-[-0.02em]">最近处理</h2></div><a href="/jobs" data-interactive="true" className="pressable text-sm font-medium text-muted-foreground hover:text-primary">全部岗位</a></div>{jobs.length ? <div className="grid gap-3 xl:grid-cols-3">{jobs.slice(0, 6).map((job) => <a key={job.id} href={`/jobs/${job.id}`} data-interactive="true" className="interactive-card group rounded-2xl border bg-white p-5"><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-slate-100 text-slate-600"><BriefcaseBusiness className="size-4" /></span><div><p className="font-semibold">{job.company}</p><p className="mt-1 text-sm text-slate-600">{job.role}</p></div></div><Badge variant="outline">{jobStatusLabels[job.status as keyof typeof jobStatusLabels] || job.status}</Badge></div><p className="mt-5 flex items-center text-xs font-medium text-muted-foreground transition group-hover:text-primary">继续处理 <ArrowUpRight className="ml-1 size-3.5 transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5" /></p></a>)}</div> : <Empty href="/jobs/new" text="还没有岗位，粘贴第一份 JD 开始匹配。" />}</section>
  </div></AppShell>;
}
function Metric({ value, label }: { value: number; label: string }) { return <div className="rounded-xl border border-slate-100 bg-slate-50/80 px-2 py-3.5"><p className="text-lg font-semibold">{value}</p><p className="mt-0.5 text-[11px] text-muted-foreground">{label}</p></div>; }
function Empty({ href, text }: { href: string; text: string }) { return <a href={href} data-interactive="true" className="interactive-card flex min-h-36 flex-col items-center justify-center rounded-2xl border border-dashed bg-white text-center text-sm text-muted-foreground"><FileText className="mb-3 size-6 text-primary" />{text}</a>; }
