'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import type { ResumeRecord } from '@/lib/server/data';
export function JobForm({ resumes }: { resumes: ResumeRecord[] }) { const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); const body = Object.fromEntries(new FormData(event.currentTarget).entries()); const response = await fetch('/api/jobs', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json() as any; setBusy(false); if (!response.ok) return setError(data.error || '创建失败'); router.push(`/jobs/${data.job.id}`); router.refresh(); } return <form onSubmit={submit} className="mx-auto max-w-3xl space-y-6 rounded-2xl border bg-white p-5 sm:p-7"><div className="grid gap-5 sm:grid-cols-2"><Field label="公司名称" name="company" required /><Field label="岗位名称" name="role" required /><Field label="工作地点" name="location" /><Field label="官网链接" name="sourceUrl" type="url" /><Field label="截止时间" name="deadline" type="date" /><label className="space-y-2 text-sm font-medium">简历语言<select name="language" className="h-10 w-full rounded-lg border bg-white px-3 font-normal"><option value="zh">中文</option><option value="en">English</option></select></label></div><div className="space-y-2"><Label htmlFor="jd">岗位描述（JD）</Label><Textarea id="jd" name="jd" required minLength={30} className="min-h-64 leading-6" placeholder="粘贴完整岗位职责与任职要求…" /></div><label className="block space-y-2 text-sm font-medium">用于匹配的基础简历<select name="resumeVersionId" className="h-10 w-full rounded-lg border bg-white px-3 font-normal"><option value="">稍后选择</option>{resumes.filter((r) => r.currentVersionId).map((r) => <option key={r.id} value={r.currentVersionId!}>{r.name} · {r.language === 'zh' ? '中文' : '英文'}</option>)}</select></label>{!resumes.length ? <p className="rounded-xl bg-amber-50 p-3 text-sm text-amber-800">尚无基础简历。可以先创建岗位，之后再到“简历版本”导入。</p> : null}{error ? <p role="alert" className="text-sm text-destructive">{error}</p> : null}<div className="flex justify-end"><Button disabled={busy} type="submit">{busy ? '正在创建…' : '创建并进入工作区'}</Button></div></form>; }
function Field({ label, name, type = 'text', required = false }: { label: string; name: string; type?: string; required?: boolean }) { return <div className="space-y-2"><Label htmlFor={name}>{label}</Label><Input id={name} name={name} type={type} required={required} /></div>; }
