'use client';
import { useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Check, Clipboard, FileDown, Sparkles, X } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';
import { jobStatusLabels, jobStatuses, type ApplicationPackContent, type JobAnalysis } from '@/lib/product-types';

type Data = any;
export function JobWorkspace({ data }: { data: Data }) {
  const router=useRouter(); const job=data.job; const versions=data.versions as any[]; const base=versions.filter(v=>!v.jobId); const branches=versions.filter(v=>v.jobId===job.id); const [selected,setSelected]=useState(base[0]?.id||''); const [busy,setBusy]=useState(''); const [message,setMessage]=useState(''); const [error,setError]=useState(''); const analysis:JobAnalysis|null=useMemo(()=>{try{return job.analysisJson?JSON.parse(job.analysisJson):null}catch{return null}},[job.analysisJson]); const pack:ApplicationPackContent|null=useMemo(()=>{try{return data.pack?.contentJson?JSON.parse(data.pack.contentJson):null}catch{return null}},[data.pack]);
  async function call(path:string,body?:unknown){setBusy(path);setError('');setMessage('');const response=await fetch(path,{method:'POST',headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const result=await response.json() as any;setBusy('');if(!response.ok){setError(result.error||'操作失败');return false;}setMessage('已完成，内容已更新。');router.refresh();return true;}
  async function status(value:string){const response=await fetch(`/api/jobs/${job.id}/status`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({status:value})});if(response.ok)router.refresh();}
  return <div className="space-y-5 pb-24"><div className="flex flex-col gap-4 rounded-2xl border bg-white p-5 md:flex-row md:items-center md:justify-between"><div className="flex flex-wrap gap-x-5 gap-y-2 text-sm text-muted-foreground"><span>{job.location||'地点未填写'}</span><span>{job.deadline?`截止 ${job.deadline}`:'截止时间未填写'}</span>{job.sourceUrl?<a className="text-primary" href={job.sourceUrl} target="_blank">打开官网 ↗</a>:null}</div><label className="flex items-center gap-2 text-sm">状态<select value={job.status} onChange={(e)=>status(e.target.value)} className="h-9 rounded-lg border bg-white px-3">{jobStatuses.map(s=><option key={s} value={s}>{jobStatusLabels[s]}</option>)}</select></label></div>
    {error?<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>:null}{message?<p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>:null}
    <Tabs defaultValue="job"><TabsList className="h-auto w-full justify-start overflow-x-auto rounded-xl bg-white p-1.5"><TabsTrigger value="job" className="px-3 py-2">岗位信息</TabsTrigger><TabsTrigger value="analysis" className="px-3 py-2">JD 分析</TabsTrigger><TabsTrigger value="tune" className="px-3 py-2">简历微调</TabsTrigger><TabsTrigger value="pack" className="px-3 py-2">填写材料</TabsTrigger><TabsTrigger value="exports" className="px-3 py-2">导出记录</TabsTrigger></TabsList>
      <TabsContent value="job"><Panel title="岗位描述" action={null}><pre className="whitespace-pre-wrap font-sans text-sm leading-7 text-slate-700">{job.jd}</pre></Panel></TabsContent>
      <TabsContent value="analysis"><Panel title="岗位匹配分析" action={<ActionSetup base={base} selected={selected} setSelected={setSelected} label={analysis?'重新分析':'开始分析'} busy={busy.includes('analyze')} disabled={!selected} onClick={()=>call(`/api/jobs/${job.id}/analyze`,{resumeVersionId:selected})} />}>{analysis?<Analysis analysis={analysis}/>:<Empty text={base.length?'选择基础简历后，AI 会提取岗位要求、关键词、优势与缺口。':'请先到“简历版本”导入一份基础简历。'} />}</Panel></TabsContent>
      <TabsContent value="tune"><div className="space-y-4"><Panel title="定向微调" action={<ActionSetup base={base} selected={selected} setSelected={setSelected} label="生成建议" busy={busy.includes('/tune')} disabled={!selected} onClick={()=>call(`/api/jobs/${job.id}/tune`,{resumeVersionId:selected})} />}>{data.suggestions?.length?<div className="space-y-3">{data.suggestions.map((s:any)=><Suggestion key={s.id} suggestion={s} onDone={()=>router.refresh()} />)}</div>:<Empty text="AI 建议会逐条展示原文、改写、理由和对应 JD。你可以接受、拒绝或编辑。" />}</Panel>{data.suggestions?.length?<div className="flex justify-end"><Button onClick={()=>call(`/api/jobs/${job.id}/resume-versions`)} disabled={busy.includes('resume-versions')||data.suggestions.some((s:any)=>s.state==='pending')}>{data.suggestions.some((s:any)=>s.state==='pending')?'请先处理全部建议':'固化为不可变岗位版本'}</Button></div>:null}</div></TabsContent>
      <TabsContent value="pack"><div className="space-y-4"><Panel title="官网填写材料包" action={<Button onClick={()=>call(`/api/jobs/${job.id}/application-pack`)} disabled={busy.includes('application-pack')}>{pack?'重新生成':'生成材料包'}</Button>}>{pack?<PackView pack={pack}/>:<Empty text="按个人信息、教育、经历、项目、技能证书和求职偏好分组，缺失值会明确标记。" />}</Panel>{pack?<CustomAnswer jobId={job.id} answers={data.answers||[]} onDone={()=>router.refresh()} />:null}</div></TabsContent>
      <TabsContent value="exports"><Panel title="岗位简历版本" action={null}>{branches.length?<div className="space-y-3">{branches.map(v=><div key={v.id} className="flex flex-col gap-3 rounded-xl border p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{v.resumeName} · v{v.versionNumber}</p><p className="mt-1 text-xs text-muted-foreground">生成于 {new Date(v.createdAt).toLocaleString('zh-CN')} · 内容快照不可变</p></div><div className="flex gap-2"><Button variant="outline" size="sm" render={<a href={`/api/resume-versions/${v.id}/export?format=docx`} />}><FileDown /> DOCX</Button><Button variant="outline" size="sm" render={<a target="_blank" href={`/api/resume-versions/${v.id}/export?format=pdf`} />}><FileDown /> PDF</Button></div></div>)}</div>:<Empty text="确认全部微调建议并固化后，这里会出现可重复导出的版本。" />}</Panel></TabsContent>
    </Tabs></div>;
}
function Panel({title,action,children}:{title:string;action:React.ReactNode;children:React.ReactNode}){return <section className="mt-3 rounded-2xl border bg-white p-5 sm:p-6"><div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h2 className="font-semibold">{title}</h2>{action}</div>{children}</section>}
function ActionSetup({base,selected,setSelected,label,busy,disabled,onClick}:{base:any[];selected:string;setSelected:(v:string)=>void;label:string;busy:boolean;disabled:boolean;onClick:()=>void}){return <div className="flex flex-col gap-2 sm:flex-row"><select value={selected} onChange={e=>setSelected(e.target.value)} className="h-9 min-w-48 rounded-lg border bg-white px-3 text-sm"><option value="">选择基础简历</option>{base.map(v=><option key={v.id} value={v.id}>{v.resumeName} v{v.versionNumber}</option>)}</select><Button onClick={onClick} disabled={disabled||busy}><Sparkles />{busy?'处理中…':label}</Button></div>}
function Analysis({analysis}:{analysis:JobAnalysis}){return <div className="grid gap-5 lg:grid-cols-[180px_1fr]"><div className="rounded-2xl bg-[#eaf8f4] p-5 text-center"><p className="text-sm text-[#397264]">当前匹配度</p><p className="mt-2 text-5xl font-semibold text-[#0b7f64]">{analysis.score}</p><p className="mt-1 text-xs text-[#397264]">/ 100</p></div><div><p className="leading-7 text-slate-700">{analysis.summary}</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><List title="已有优势" items={analysis.strengths}/><List title="待补缺口" items={analysis.gaps}/><List title="硬性要求" items={analysis.mustHave}/><List title="关键词" items={analysis.keywords}/></div></div></div>}
function List({title,items}:{title:string;items:string[]}){return <div className="rounded-xl border p-4"><p className="font-medium">{title}</p><ul className="mt-3 space-y-2 text-sm leading-6 text-muted-foreground">{items.map((x,i)=><li key={i}>• {x}</li>)}</ul></div>}
function Suggestion({suggestion:s,onDone}:{suggestion:any;onDone:()=>void}){const [edit,setEdit]=useState(s.editedText||s.proposedText);const [busy,setBusy]=useState(false);async function update(state:string){setBusy(true);const response=await fetch(`/api/suggestions/${s.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({state,editedText:edit})});setBusy(false);if(response.ok)onDone();}return <article className="rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><Badge variant={s.needsUserInput?'destructive':'outline'}>{s.needsUserInput?'待补充事实':s.sectionKey}</Badge><span className="text-xs text-muted-foreground">{s.state==='pending'?'待处理':s.state==='accepted'?'已接受':'已拒绝'}</span></div><div className="mt-4 grid gap-4 lg:grid-cols-2"><div><p className="text-xs font-medium text-muted-foreground">原文</p><p className="mt-2 rounded-lg bg-slate-50 p-3 leading-6">{s.originalText}</p></div><div><p className="text-xs font-medium text-muted-foreground">建议文本（可编辑）</p><Textarea className="mt-2 min-h-28" value={edit} onChange={e=>setEdit(e.target.value)} /></div></div><div className="mt-3 grid gap-2 text-sm leading-6 text-muted-foreground"><p><span className="font-medium text-foreground">理由：</span>{s.rationale}</p><p><span className="font-medium text-foreground">对应 JD：</span>{s.matchedRequirement}</p></div><div className="mt-4 flex justify-end gap-2"><Button size="sm" variant="outline" disabled={busy} onClick={()=>update('rejected')}><X />拒绝</Button><Button size="sm" disabled={busy||s.needsUserInput} onClick={()=>update('accepted')}><Check />接受{edit!==s.proposedText?'编辑稿':''}</Button></div></article>}
function PackView({pack}:{pack:ApplicationPackContent}){const [copied,setCopied]=useState('');async function copy(id:string,value:string){await navigator.clipboard.writeText(value);setCopied(id);setTimeout(()=>setCopied(''),1200)}return <div className="space-y-5">{pack.missingFields.length?<div className="rounded-xl bg-amber-50 p-4 text-sm text-amber-900"><p className="font-medium">缺失 {pack.missingFields.length} 项</p><p className="mt-1 leading-6">{pack.missingFields.join('、')}</p></div>:null}{pack.groups.map(g=><section key={g.id}><div className="mb-2 flex items-center justify-between"><h3 className="font-medium">{g.title}</h3><button onClick={()=>copy(g.id,g.fields.map(f=>`${f.label}：${f.value}`).join('\n'))} className="text-xs text-primary">整组复制</button></div><div className="divide-y rounded-xl border">{g.fields.map(f=><div key={f.id} className="grid gap-2 p-4 sm:grid-cols-[150px_1fr_auto]"><div><p className="text-sm font-medium">{f.label}</p><p className="mt-1 text-xs text-muted-foreground">{f.source}</p></div><p className={f.missing?'text-amber-700':'whitespace-pre-wrap text-sm leading-6'}>{f.missing?'待补充':f.value}<span className="ml-2 text-xs text-muted-foreground">{f.value.length} 字</span></p><button disabled={f.missing} onClick={()=>copy(f.id,f.value)} className="h-fit text-xs text-primary disabled:text-slate-300"><Clipboard className="mr-1 inline size-3.5"/>{copied===f.id?'已复制':'复制'}</button></div>)}</div></section>)}</div>}
function CustomAnswer({jobId,answers,onDone}:{jobId:string;answers:any[];onDone:()=>void}){const [question,setQuestion]=useState('');const [limit,setLimit]=useState('300');const [busy,setBusy]=useState(false);const [error,setError]=useState('');async function submit(){setBusy(true);setError('');const response=await fetch(`/api/jobs/${jobId}/custom-answers`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({question,charLimit:limit?Number(limit):undefined})});const data=await response.json() as any;setBusy(false);if(!response.ok)return setError(data.error||'生成失败');setQuestion('');onDone();}return <Panel title="临时开放题" action={null}><div className="grid gap-3 sm:grid-cols-[1fr_130px_auto]"><Input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="粘贴官网问题"/><Input value={limit} onChange={e=>setLimit(e.target.value)} type="number" min="20" max="5000" aria-label="字数限制"/><Button onClick={submit} disabled={busy||question.trim().length<3}>{busy?'生成中…':'生成答案'}</Button></div>{error?<p className="mt-3 text-sm text-destructive">{error}</p>:null}{answers.length?<div className="mt-5 space-y-3">{answers.map(a=><div key={a.id} className="rounded-xl border p-4"><p className="font-medium">{a.question}</p><p className="mt-2 whitespace-pre-wrap leading-6 text-slate-700">{a.answer}</p><button className="mt-3 text-xs text-primary" onClick={()=>navigator.clipboard.writeText(a.answer)}>复制答案 · {a.answer.length} 字{a.charLimit?` / ${a.charLimit}`:''}</button></div>)}</div>:null}</Panel>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed p-10 text-center text-sm leading-6 text-muted-foreground">{text}</div>}
