'use client';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import type { Profile } from '@/lib/product-types';

export function ProfileEditor({ initial }: { initial: Profile }) {
  const [profile, setProfile] = useState(initial); const [state, setState] = useState<'idle'|'saving'|'saved'>('idle'); const [error, setError] = useState('');
  const identity = profile.identity;
  const setIdentity = (key: keyof typeof identity, value: string) => setProfile((p) => ({ ...p, identity: { ...p.identity, [key]: value } }));
  const setList = (key: 'skills'|'certificates'|'awards'|'languages', value: string) => setProfile((p) => ({ ...p, [key]: value.split(/[，,\n]/).map((v) => v.trim()).filter(Boolean) }));
  async function save() { setState('saving'); setError(''); const response = await fetch('/api/profile', { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify(profile) }); const data = await response.json() as any; if (!response.ok) { setError(data.error || '保存失败'); setState('idle'); return; } setState('saved'); setTimeout(() => setState('idle'), 1800); }
  return <div className="mx-auto max-w-5xl space-y-5 pb-24"><section className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-900"><p className="font-medium">敏感信息存储提示</p><p>身份证号等字段会以普通数据库字段保存，不增加应用层加密；它们不会被发送给 AI。只填写官网投递确实需要的内容。</p></section>
    <Section title="基础信息" description="AI 分析时会自动隐藏联系方式、证件号和详细地址。"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="姓名" value={identity.name} onChange={(v) => setIdentity('name', v)} /><Field label="邮箱" value={identity.email} onChange={(v) => setIdentity('email', v)} /><Field label="手机" value={identity.phone} onChange={(v) => setIdentity('phone', v)} /><Field label="所在地" value={identity.location} onChange={(v) => setIdentity('location', v)} /><Field label="出生日期" value={identity.birthDate} type="date" onChange={(v) => setIdentity('birthDate', v)} /><Field label="身份证号（可选）" value={identity.idNumber} onChange={(v) => setIdentity('idNumber', v)} /></div></Section>
    <Section title="教育经历"><div className="space-y-4">{profile.education.map((entry,index)=><div key={entry.id} className="rounded-xl border p-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Field label="学校" value={entry.school} onChange={v=>setProfile(p=>({...p,education:p.education.map((e,i)=>i===index?{...e,school:v}:e)}))}/><Field label="学位" value={entry.degree} onChange={v=>setProfile(p=>({...p,education:p.education.map((e,i)=>i===index?{...e,degree:v}:e)}))}/><Field label="专业" value={entry.major} onChange={v=>setProfile(p=>({...p,education:p.education.map((e,i)=>i===index?{...e,major:v}:e)}))}/><Field label="GPA / 排名" value={[entry.gpa,entry.rank].filter(Boolean).join(' / ')} onChange={v=>setProfile(p=>({...p,education:p.education.map((e,i)=>i===index?{...e,gpa:v}:e)}))}/><Field label="开始时间" type="month" value={entry.startDate} onChange={v=>setProfile(p=>({...p,education:p.education.map((e,i)=>i===index?{...e,startDate:v}:e)}))}/><Field label="结束时间" type="month" value={entry.endDate} onChange={v=>setProfile(p=>({...p,education:p.education.map((e,i)=>i===index?{...e,endDate:v}:e)}))}/></div><button className="mt-3 text-xs text-destructive" onClick={()=>setProfile(p=>({...p,education:p.education.filter((_,i)=>i!==index)}))}>删除此条</button></div>)}<Button type="button" variant="outline" onClick={()=>setProfile(p=>({...p,education:[...p.education,{id:crypto.randomUUID(),school:'',degree:'',major:'',startDate:'',endDate:'',gpa:'',rank:'',highlights:[]}]}))}>+ 添加教育经历</Button></div></Section>
    <ExperienceSection title="实习 / 工作经历" entries={profile.experiences} onChange={entries=>setProfile(p=>({...p,experiences:entries}))}/>
    <ExperienceSection title="项目经历" entries={profile.projects} onChange={entries=>setProfile(p=>({...p,projects:entries}))}/>
    <Section title="能力与资质"><div className="grid gap-4 sm:grid-cols-2"><ListField label="技能" value={profile.skills.join('，')} onChange={(v) => setList('skills', v)} placeholder="SQL，Python，Figma" /><ListField label="语言" value={profile.languages.join('，')} onChange={(v) => setList('languages', v)} placeholder="英语 CET-6，普通话" /><ListField label="证书" value={profile.certificates.join('，')} onChange={(v) => setList('certificates', v)} /><ListField label="奖项" value={profile.awards.join('，')} onChange={(v) => setList('awards', v)} /></div></Section>
    <Section title="自我评价"><div className="grid gap-4 lg:grid-cols-2"><ListField label="中文版" rows={6} value={profile.summaries.zh} onChange={(v) => setProfile((p) => ({...p,summaries:{...p.summaries,zh:v}}))} /><ListField label="English" rows={6} value={profile.summaries.en} onChange={(v) => setProfile((p) => ({...p,summaries:{...p.summaries,en:v}}))} /></div></Section>
    <Section title="求职偏好"><div className="grid gap-4 sm:grid-cols-2"><ListField label="目标岗位（逗号分隔）" value={profile.preferences.desiredRoles.join('，')} onChange={(v) => setProfile((p) => ({...p,preferences:{...p.preferences,desiredRoles:v.split(/[，,]/).map(x=>x.trim()).filter(Boolean)}}))} /><ListField label="目标城市（逗号分隔）" value={profile.preferences.desiredLocations.join('，')} onChange={(v) => setProfile((p) => ({...p,preferences:{...p.preferences,desiredLocations:v.split(/[，,]/).map(x=>x.trim()).filter(Boolean)}}))} /><Field label="到岗时间" value={profile.preferences.availability} onChange={(v) => setProfile((p) => ({...p,preferences:{...p.preferences,availability:v}}))} /><Field label="期望薪资" value={profile.preferences.expectedSalary} onChange={(v) => setProfile((p) => ({...p,preferences:{...p.preferences,expectedSalary:v}}))} /></div></Section>
    {error ? <p role="alert" className="text-sm text-destructive">{error}</p> : null}<div className="sticky bottom-16 flex justify-end rounded-2xl border bg-white/90 p-3 shadow-lg backdrop-blur lg:bottom-4"><Button onClick={save} disabled={state === 'saving'}>{state === 'saving' ? '保存中…' : state === 'saved' ? '已保存 ✓' : '保存事实档案'}</Button></div>
  </div>;
}
function Section({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) { return <section className="rounded-2xl border bg-white p-5 sm:p-6"><h2 className="font-semibold">{title}</h2>{description ? <p className="mt-1 text-sm text-muted-foreground">{description}</p> : null}<div className="mt-5">{children}</div></section>; }
function Field({ label, value, onChange, type='text' }: { label: string; value: string; onChange: (v:string)=>void; type?: string }) { const id = `f-${label}`; return <div className="space-y-2"><Label htmlFor={id}>{label}</Label><Input id={id} type={type} value={value} onChange={(e)=>onChange(e.target.value)} /></div>; }
function ListField({ label, value, onChange, placeholder, rows=3 }: { label:string; value:string; onChange:(v:string)=>void; placeholder?:string; rows?:number }) { const id=`l-${label}`; return <div className="space-y-2"><Label htmlFor={id}>{label}</Label><Textarea id={id} rows={rows} value={value} placeholder={placeholder} onChange={(e)=>onChange(e.target.value)} /></div>; }
function ExperienceSection({title,entries,onChange}:{title:string;entries:Profile['experiences'];onChange:(entries:Profile['experiences'])=>void}){return <Section title={title}><div className="space-y-4">{entries.map((entry,index)=>{const update=(key:keyof typeof entry,value:any)=>onChange(entries.map((e,i)=>i===index?{...e,[key]:value}:e));return <div key={entry.id} className="rounded-xl border p-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Field label="名称 / 职位" value={entry.title} onChange={v=>update('title',v)}/><Field label="组织 / 公司" value={entry.organization} onChange={v=>update('organization',v)}/><Field label="地点" value={entry.location} onChange={v=>update('location',v)}/><Field label="开始时间" type="month" value={entry.startDate} onChange={v=>update('startDate',v)}/><Field label="结束时间" type="month" value={entry.endDate} onChange={v=>update('endDate',v)}/></div><div className="mt-3"><ListField label="事实亮点（每行一条）" rows={4} value={entry.highlights.join('\n')} onChange={v=>update('highlights',v.split('\n').map(x=>x.trim()).filter(Boolean))}/></div><button className="mt-3 text-xs text-destructive" onClick={()=>onChange(entries.filter((_,i)=>i!==index))}>删除此条</button></div>})}<Button type="button" variant="outline" onClick={()=>onChange([...entries,{id:crypto.randomUUID(),title:'',organization:'',startDate:'',endDate:'',location:'',highlights:[]}])}>+ 添加{title}</Button></div></Section>}
